DEBUG = True

ORIGIN = 0, 0

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

FPS = 60

# Size of each Cell object in pixels
BIT_DEPTH = 16

FONT_SIZE = 18

# GUI Dimensions
GUI_WIDTH = WINDOW_WIDTH
GUI_HEIGHT = 64
GUI_SIZE = (GUI_WIDTH, GUI_HEIGHT)
GUI_DEST = ORIGIN

# Grid Dimensions
GRID_WIDTH = WINDOW_WIDTH
GRID_HEIGHT = WINDOW_HEIGHT - GUI_HEIGHT
GRID_SIZE = (GRID_WIDTH, GRID_HEIGHT)
GRID_DEST = (0, GUI_HEIGHT)

# Number of Cell objects per Column and Row
COLUMNS = GRID_WIDTH // BIT_DEPTH
ROWS = GRID_HEIGHT // BIT_DEPTH
